name: Decode JavaScript File

on:
  workflow_dispatch:

jobs:
  decode:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install npm dependencies
      run: npm install

    - name: Run npm decode script
      run: npm run decode -- [-i input.js] [-o output.js]

    - name: Execute Python script for additional decoding
      run: python src/decode.py

    - name: Configure Git author
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "action"

    - name: Save decoded output to repository
      run: |
        git status
        git add output.js output.py
        git diff --cached --exit-code || git commit -m "Add decoded output file"
        git push
